# Pytorch 学习
## 一、张量
1. ### 张量的概念： 
张量（Tensor）是 PyTorch 中的核心数据结构，用于存储和操作多维数组。

2. ### 张量的属性： 
（1）张量的维度是指张量的秩，秩是指张量中元素数量的个数，一维可看做是一个数组，二维可看做矩阵，三维可看做三维空间中的点，四维可看做四维空间中的点云。 
> .dim()  返回秩

（2）张量的形状是指张量的各个维度的长度。  
> 例如：一个3x4的矩阵，它的秩为2，形状为(3,4)。
> print(g.shape)  返回形状
> print(g.size())  同上

（3）张量的数据类型是指张量中元素的类型,支持多种数据类型（整型、浮点型、布尔型等）  
> 例如：一个3x4的矩阵，它的元素类型可以是整数、浮点数、布尔值等。  
> print(g.dtype)  返回类型

（3）张量的设备检查：
> 张量可以存储在CPU或者GPU上，可以通过.device属性来查看张量所在的设备。  
> .is_cuda  判断张量是否在GPU上

 (4)张量转置：
> 张量的转置操作是指将张量的行列互换，例如一个3x4的矩阵，它的转置操作可以得到4x3的矩阵。  
> g.t()  转置

3. ### 张量的创建：

In [ ]:
import torch
#创建张量
x = torch.tensor([1,2,3])
print(x)
#创建随机张量
c = torch.rand(3,4)
print(c)
#创建全零张量
z = torch.zeros(2,3)
print(z)
#创建全一张量
o = torch.ones(2,3)
print(o)
#创建单位矩阵
I = torch.eye(3)
print(I)
#将numpy数组转换为张量
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = torch.from_numpy(a)
print(b)
#将张量转换为numpy数组
c = b.numpy()
print(c)

tensor([1, 2, 3])
tensor([[0.0876, 0.8373, 0.6534, 0.2927],
        [0.3609, 0.0971, 0.6540, 0.2159],
        [0.3262, 0.3425, 0.8255, 0.8411]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


4. 对张量的操作：

In [1]:
import torch

# 创建一个 2D 张量
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("原始张量:\n", tensor)

# 1. **索引和切片操作**
print("\n【索引和切片】")
print("获取第一行:", tensor[0])
print("获取第一行第一列的元素:", tensor[0, 0]) 
print("获取第二列的所有元素:", tensor[:, 1]) 

# 2. **形状变换操作**
print("\n【形状变换】")
reshaped = tensor.view(3, 2) 
print("改变形状后的张量:\n", reshaped)
flattened = tensor.flatten() 
print("展平后的张量:\n", flattened)

# 3. **数学运算操作**
print("\n【数学运算】")
tensor_add = tensor + 10 
print("张量加 10:\n", tensor_add)
tensor_mul = tensor * 2 
print("张量乘 2:\n", tensor_mul)
tensor_sum = tensor.sum() 
print("张量元素的和:", tensor_sum.item())

# 4. **与其他张量的操作**
print("\n【与其他张量操作】")
tensor2 = torch.tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.float32)
print("另一个张量:\n", tensor2)
tensor_dot = torch.matmul(tensor, tensor2.T) 
print("矩阵乘法结果:\n", tensor_dot)

# 5. **条件判断和筛选**
print("\n【条件判断和筛选】")
mask = tensor > 3 
print("大于 3 的元素的布尔掩码:\n", mask)
filtered_tensor = tensor[tensor > 3] 
print("大于 3 的元素:\n", filtered_tensor)

原始张量:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

【索引和切片】
获取第一行: tensor([1., 2., 3.])
获取第一行第一列的元素: tensor(1.)
获取第二列的所有元素: tensor([2., 5.])

【形状变换】
改变形状后的张量:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
展平后的张量:
 tensor([1., 2., 3., 4., 5., 6.])

【数学运算】
张量加 10:
 tensor([[11., 12., 13.],
        [14., 15., 16.]])
张量乘 2:
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
张量元素的和: 21.0

【与其他张量操作】
另一个张量:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
矩阵乘法结果:
 tensor([[ 6.,  6.],
        [15., 15.]])

【条件判断和筛选】
大于 3 的元素的布尔掩码:
 tensor([[False, False, False],
        [ True,  True,  True]])
大于 3 的元素:
 tensor([4., 5., 6.])


5. 张量的GPU加速
> 将张量转移到GPU上进行加速运算，可以显著提升运算速度
> 检查GPU是否可用

In [2]:
import torch
#转移
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([1.0, 2.0, 3.0], device=device)

#检查
torch.cuda.is_available() #返回布尔值

True

6. 梯度与自动微分
张量支持自动微分，可自动计算梯度。

In [3]:
# 创建一个需要梯度的张量
tensor_requires_grad = torch.tensor([1.0], requires_grad=True)

# 进行一些操作
tensor_result = tensor_requires_grad * 2

# 计算梯度
tensor_result.backward()
print(tensor_requires_grad.grad)  

tensor([2.])


7. 自动求导


In [2]:
import torch

# 创建一个需要计算梯度的张量
x = torch.randn(2, 2, requires_grad=True)
print(x)

y = x + 2
z = y * y * 3
out = z.mean()

print(out)

tensor([[ 0.5942, -0.6803],
        [ 0.1916, -1.2811]], requires_grad=True)
tensor(10.3438, grad_fn=<MeanBackward0>)


##二、神经网络基础    
###1. 创建简单的神经网络

In [3]:
import torch.nn as nn
import torch.optim as optim

# 定义一个简单的全连接神经网络
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # 输入层到隐藏层
        self.fc2 = nn.Linear(2, 1)  # 隐藏层到输出层
   
    def forward(self, x):
        x = torch.relu(self.fc1(x))  # ReLU 激活函数
        x = self.fc2(x)
        return x

# 创建网络实例
model = SimpleNN()

# 打印模型结构
print(model)

SimpleNN(
  (fc1): Linear(in_features=2, out_features=2, bias=True)
  (fc2): Linear(in_features=2, out_features=1, bias=True)
)


###2. 第一个神经网络

In [8]:
# 导入PyTorch库
import torch
import torch.nn as nn

# 定义输入层大小、隐藏层大小、输出层大小和批量大小
n_in, n_h, n_out, batch_size = 10, 5, 1, 10

# 创建虚拟输入数据和目标数据
x = torch.randn(batch_size, n_in)  # 随机生成输入数据
y = torch.tensor([[1.0], [0.0], [0.0],
                 [1.0], [1.0], [1.0], [0.0], [0.0], [1.0], [1.0]])  # 目标输出数据

# 创建顺序模型，包含线性层、ReLU激活函数和Sigmoid激活函数
model = nn.Sequential(
   nn.Linear(n_in, n_h),  # 输入层到隐藏层的线性变换
   nn.ReLU(),            # 隐藏层的ReLU激活函数
   nn.Linear(n_h, n_out),  # 隐藏层到输出层的线性变换
   nn.Sigmoid()           # 输出层的Sigmoid激活函数
)

# 定义均方误差损失函数和随机梯度下降优化器
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)  # 学习率为0.01

# 执行梯度下降算法进行模型训练
for epoch in range(50):  # 迭代50次
   y_pred = model(x)  # 前向传播，计算预测值
   loss = criterion(y_pred, y)  # 计算损失
   print('epoch: ', epoch, 'loss: ', loss.item())  # 打印损失值

   optimizer.zero_grad()  # 清零梯度
   loss.backward()  # 反向传播，计算梯度
   optimizer.step()  # 更新模型参数

epoch:  0 loss:  0.24839134514331818
epoch:  1 loss:  0.24821177124977112
epoch:  2 loss:  0.24803271889686584
epoch:  3 loss:  0.2478541135787964
epoch:  4 loss:  0.24767610430717468
epoch:  5 loss:  0.24749855697155
epoch:  6 loss:  0.24732151627540588
epoch:  7 loss:  0.2471449375152588
epoch:  8 loss:  0.24696889519691467
epoch:  9 loss:  0.24679331481456757
epoch:  10 loss:  0.24661822617053986
epoch:  11 loss:  0.24644359946250916
epoch:  12 loss:  0.24626943469047546
epoch:  13 loss:  0.24609582126140594
epoch:  14 loss:  0.24592263996601105
epoch:  15 loss:  0.24574990570545197
epoch:  16 loss:  0.2455776184797287
epoch:  17 loss:  0.24540583789348602
epoch:  18 loss:  0.2452344447374344
epoch:  19 loss:  0.24506357312202454
epoch:  20 loss:  0.2448931187391281
epoch:  21 loss:  0.24472308158874512
epoch:  22 loss:  0.2445535659790039
epoch:  23 loss:  0.24438443779945374
epoch:  24 loss:  0.244215726852417
epoch:  25 loss:  0.24404747784137726
epoch:  26 loss:  0.2438796311616

##三、数据处理与加载
###1. 自定义Dataset

In [11]:
import torch
from torch.utils.data import Dataset

# 自定义数据集类
class MyDataset(Dataset):
    def __init__(self, X_data, Y_data):
        self.X_data = X_data
        self.Y_data = Y_data

    def __len__(self):
        """返回数据集的大小"""
        return len(self.X_data)

    def __getitem__(self, idx):
        """返回指定索引的数据"""
        x = torch.tensor(self.X_data[idx], dtype=torch.float32) # 转换为 Tensor
        y = torch.tensor(self.Y_data[idx], dtype=torch.float32)
        return x, y

# 示例数据
X_data = [[1, 2], [3, 4], [5, 6], [7, 8]] # 输入特征
Y_data = [1, 0, 1, 0] # 目标标签

# 创建数据集实例
dataset = MyDataset(X_data, Y_data)

###2. DataLoader 加载数据

In [12]:
from torch.utils.data import DataLoader

# 创建 DataLoader 实例，batch_size 设置每次加载的样本数量
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# 打印加载的数据
for epoch in range(1):
    for batch_idx, (inputs, labels) in enumerate(dataloader):
        print(f'Batch {batch_idx + 1}:')
        print(f'Inputs: {inputs}')
        print(f'Labels: {labels}')

Batch 1:
Inputs: tensor([[3., 4.],
        [5., 6.]])
Labels: tensor([0., 1.])
Batch 2:
Inputs: tensor([[1., 2.],
        [7., 8.]])
Labels: tensor([1., 0.])


##四、数据集
###1. Dataset类

In [14]:
import torch
from torch.utils.data import Dataset

# 自定义数据集
class MyDataset(Dataset):
    def __init__(self, data, labels):
        # 数据初始化
        self.data = data
        self.labels = labels

    def __len__(self):
        # 返回数据集大小
        return len(self.data)

    def __getitem__(self, idx):
        # 按索引返回数据和标签
        sample = self.data[idx]
        label = self.labels[idx]
        return sample, label

# 生成示例数据
data = torch.randn(100, 5)  # 100 个样本，每个样本有 5 个特征
labels = torch.randint(0, 2, (100,))  # 100 个标签，取值为 0 或 1

# 实例化数据集
dataset = MyDataset(data, labels)

# 测试数据集
print("数据集大小:", len(dataset))
print("第 0 个样本:", dataset[0])

数据集大小: 100
第 0 个样本: (tensor([ 0.1774, -0.5163, -1.4653,  0.9251, -0.0267]), tensor(0))


###2. DataLoaders

In [15]:
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

# 自定义数据集
class MyDataset(Dataset):
    def __init__(self, data, labels):
        # 数据初始化
        self.data = data
        self.labels = labels

    def __len__(self):
        # 返回数据集大小
        return len(self.data)

    def __getitem__(self, idx):
        # 按索引返回数据和标签
        sample = self.data[idx]
        label = self.labels[idx]
        return sample, label

# 生成示例数据
data = torch.randn(100, 5)  # 100 个样本，每个样本有 5 个特征
labels = torch.randint(0, 2, (100,))  # 100 个标签，取值为 0 或 1

# 实例化数据集
dataset = MyDataset(data, labels)
# 实例化 DataLoader
dataloader = DataLoader(dataset, batch_size=10, shuffle=True, num_workers=0)

# 遍历 DataLoader
for batch_idx, (batch_data, batch_labels) in enumerate(dataloader):
    print(f"批次 {batch_idx + 1}")
    print("数据:", batch_data)
    print("标签:", batch_labels)
    if batch_idx == 2:  # 仅显示前 3 个批次
        break

批次 1
数据: tensor([[ 0.3995, -0.2506,  1.2575,  1.4829, -0.4648],
        [-0.9211,  0.9862, -0.8771, -0.5299,  0.2593],
        [ 0.6533,  2.1652, -0.5321,  0.1677,  0.2277],
        [ 1.7109,  1.6551, -0.4611, -0.5387,  0.1038],
        [ 1.1513,  0.7928, -1.0680, -1.5302, -0.6365],
        [ 0.2114, -0.2996, -0.0025,  0.7946,  0.3224],
        [-0.6230, -0.5963, -1.1038,  1.1768,  1.5314],
        [-0.0418,  0.7482,  0.0982, -1.0948,  1.3369],
        [-0.5062,  1.0496,  0.1247,  0.0111,  1.7290],
        [-0.2552, -0.6193,  0.5204, -1.6448,  0.0638]])
标签: tensor([0, 0, 0, 1, 1, 1, 1, 0, 0, 0])
批次 2
数据: tensor([[-2.1926, -1.0206,  0.2850, -0.2766, -1.8185],
        [ 0.4735, -1.0229, -0.1064,  0.4118, -0.2687],
        [-1.3911, -2.0342, -1.5711,  1.4035, -0.3321],
        [-0.6951,  0.0629,  0.9292, -0.6653, -1.0978],
        [-0.2986, -0.6654, -0.6392,  0.2306, -0.6792],
        [ 0.5365, -0.3769, -0.2262,  0.3272, -1.2582],
        [ 1.7093,  0.2828,  1.4366, -1.4886, -0.1768],
   

###3. 内置数据集

In [16]:
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

# 定义数据预处理
transform = transforms.Compose([
    transforms.ToTensor(),  # 转换为张量
    transforms.Normalize((0.5,), (0.5,))  # 标准化
])

# 加载训练数据集
train_dataset = torchvision.datasets.MNIST(
    root='./data', train=True, transform=transform, download=True)

# 使用 DataLoader 加载数据
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# 查看一个批次的数据
data_iter = iter(train_loader)
images, labels = next(data_iter)
print(f"批次图像大小: {images.shape}")  # 输出形状为 [batch_size, 1, 28, 28]
print(f"批次标签: {labels}")

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100.0%

Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw

批次图像大小: torch.Size([32, 1, 28, 28])
批次标签: tensor([7, 6, 2, 1, 0, 3, 8, 8, 2, 3, 6, 3, 5, 0, 5, 8, 8, 5, 6, 1, 9, 7, 6, 5,
        0, 6, 5, 1, 3, 0, 5, 1])


##五、数据转换
###对图像数据集应用转换

In [17]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# 定义转换
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# 加载数据集
train_dataset = datasets.MNIST(root='./data', train=True, transform=transform, download=True)

# 使用 DataLoader
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)

# 查看转换后的数据
for images, labels in train_loader:
    print("图像张量大小:", images.size())  # [batch_size, 1, 128, 128]
    break

图像张量大小: torch.Size([32, 1, 128, 128])
